# Generated by Django 4.2.16 on 2026-05-12 14:44

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='用户唯一登录账号，不可重复', max_length=100, unique=True, verbose_name='登录邮箱')),
                ('password', models.CharField(help_text='存储加密后的密码，不存储明文', max_length=255, verbose_name='加密密码')),
                ('username', models.CharField(default='默认用户', help_text='显示用昵称，可修改，允许重复', max_length=50, verbose_name='用户昵称')),
                ('phone', models.CharField(blank=True, help_text='可选，用于账号找回、短信通知，需唯一', max_length=15, null=True, unique=True, verbose_name='手机号码')),
                ('avatar', models.ImageField(blank=True, help_text='可选，默认使用系统占位图', null=True, upload_to='avatar/', verbose_name='用户头像')),
                ('gender', models.CharField(choices=[('MALE', '男'), ('FEMALE', '女'), ('OTHER', '其他'), ('SECRET', '保密')], default='SECRET', help_text='默认保密', max_length=10, verbose_name='性别')),
                ('birthday', models.DateField(blank=True, help_text='可选，用于个性化功能（如生日提醒）', null=True, verbose_name='出生日期')),
                ('is_banned', models.BooleanField(default=False, help_text='False为正常状态；True时账号被永久封禁，需管理员手动解封', verbose_name='是否被永久封禁')),
                ('ban_reason', models.TextField(blank=True, help_text='记录永久封禁的原因，如违反平台规则等', null=True, verbose_name='封禁原因')),
                ('ban_time', models.DateTimeField(blank=True, help_text='账号被永久封禁时的时间，自动记录', null=True, verbose_name='封禁时间')),
                ('is_staff', models.BooleanField(default=False, help_text='True时可登录Django后台管理系统，管理数据', verbose_name='是否为管理员')),
                ('user_role', models.CharField(choices=[('NORMAL', '普通用户'), ('VIP', '会员用户'), ('ADMIN', '系统管理员')], default='NORMAL', help_text='控制功能权限（如普通用户无数据导出权限）', max_length=20, verbose_name='用户角色')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, help_text='记录用户上次登录的IP地址，用于安全审计', null=True, verbose_name='上次登录IP')),
                ('last_login_time', models.DateTimeField(blank=True, help_text='记录用户上次登录的时间', null=True, verbose_name='上次登录时间')),
                ('login_count', models.PositiveIntegerField(default=0, help_text='统计用户成功登录的总次数，每次登录自动+1', verbose_name='累计登录次数')),
                ('password_reset_time', models.DateTimeField(blank=True, help_text='用于提示用户定期修改密码，增强安全性', null=True, verbose_name='密码最后修改时间')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='用户账号创建时间，自动生成', verbose_name='注册时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='用户信息修改时自动更新', verbose_name='信息更新时间')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserVerifyCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='接收验证码的用户邮箱', max_length=100, verbose_name='用户邮箱')),
                ('verify_code', models.CharField(help_text='随机生成的6位数字验证码', max_length=6, verbose_name='6位验证码')),
                ('expire_time', models.DateTimeField(help_text='验证码有效期（默认5分钟）', verbose_name='过期时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='验证码生成时间', verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '用户验证码',
                'verbose_name_plural': '用户验证码',
                'indexes': [models.Index(fields=['email'], name='weather_app_email_87b6cc_idx'), models.Index(fields=['email', 'expire_time'], name='weather_app_email_106f83_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='userverifycode',
            constraint=models.UniqueConstraint(condition=models.Q(('expire_time__gt', datetime.datetime(2026, 5, 12, 14, 44, 45, 793132, tzinfo=datetime.timezone.utc))), fields=('email',), name='unique_active_verify_code'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='weather_app_email_c585e1_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['phone'], name='weather_app_phone_f6a057_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['created_at'], name='weather_app_created_d59ed5_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_banned'], name='weather_app_is_bann_5deb11_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['user_role', 'is_banned'], name='weather_app_user_ro_4ea47d_idx'),
        ),
    ]
